[package]
name = "microarrow"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"
flatbuffers = "25.12.19"
zstd = { version = "0.13.3", default-features = false, optional = true }

[features]
zstd = ["dep:zstd"]
default = ["zstd"]

[dev-dependencies]
arrow-array = "58.3.0"
arrow-ipc = "58.3.0"
