[package]
name = "picoarrow"
description = "Statically typed implementation of a subset of Apache Arrow"
version = "0.2.2"
edition = "2024"
license = "MPL-2.0"
authors = ["Andrej Kolčin <self@kaathewise.net>"]
repository = "https://github.com/kaathewisegit/picoarrow"
keywords = ["arrow", "arrow-ipc"]
categories = ["encoding"]

[dependencies]
bytemuck = "1.25.0"
flatbuffers = "25.12.19"
half = { version = "2.7.1", optional = true, features = ["bytemuck"] }
lz4_flex = { version = "0.13.1", optional = true, default-features = false, features = ["frame"] }
zstd = { version = "0.13.3", optional = true, default-features = false }

[features]
default = ["zstd"]
lz4 = ["dep:lz4_flex"]
zstd = ["dep:zstd"]
half = ["dep:half"]

[dev-dependencies]
arbitrary = { version = "1.4.2" }
arbtest = "0.3.2"
arrow-array = "58.3.0"
arrow-ipc = { version = "58.3.0", features = ["zstd", "lz4"] }
arrow-schema = "58.3.0"
half = { version = "2.7.1", features = ["arbitrary"] }
pastey = "0.2.3"

[lints.rust]
warnings = "deny"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
	"--cfg", "docsrs",
	"--generate-link-to-definition",
	"--generate-macro-expansion",
]
