[package]
name = "picoarrow"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"
flatbuffers = "25.12.19"
lz4_flex = { version = "0.13.1", optional = true, default-features = false, features = ["frame"] }
zstd = { version = "0.13.3", optional = true, default-features = false }

[features]
default = ["zstd"]
lz4 = ["dep:lz4_flex"]
zstd = ["dep:zstd"]

[dev-dependencies]
arrow-array = "58.3.0"
arrow-ipc = "58.3.0"
