name: Check

on: [push, pull_request]

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-24.04, macos-14, windows-2022]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v7

      - name: cache target
        uses: actions/cache@v5
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-target-

      - run: sh check.sh --full
