name: Check

on: [push, pull_request]

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-24.04, macos-14, windows-2022]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6

      - run: sh check.sh
